name: iOS starter workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
    
    - name: Install CocoaPods
      run: |
        gem install cocoapods
        pod install --project-directory=oldy-app/oldy-app/oldy-app.xcodeproj

    - name: Build and test
      run: |
        xcodebuild -workspace oldy-app/oldy-app/oldy-app.xcodeproj/project.xcworkspace \
                   -scheme oldy-app \
                   -destination 'platform=iOS Simulator,name=iPhone 11,OS=latest' \
                   clean test
